Changes for the 1.1 release. See README.xml for details.
git-svn-id: https://godirepo.camlcity.org/svn/lib-findlib/trunk@76 5e68ba05-c9cc-0310-a7d4-dca2aa431786

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,7 +7,7 @@
 
 #set -x
 
-version="1.0.4"
+version="1.1"
 
 # Remember the old IFS value:
 oldifs="$IFS"
@@ -371,6 +371,25 @@ case `uname` in
     true ;;
 esac
 
+######################################################################
+
+printf "Detecting compiler arguments: "
+
+( cd tools/extract_args && make ) >ocargs.log 2>&1
+if [ "$?" -eq 0 ]; then
+    printf "(extractor built) "
+    tools/extract_args/extract_args -o src/findlib/ocaml_args.ml ocamlc ocamlcp ocamlmktop ocamlopt ocamldep ocamldoc >>ocargs.log 2>&1
+    # ocamlbrowser does not work!
+    if [ $? -eq 0 ]; then
+	echo "ok"
+    else
+	echo "FAILED"
+	exit 1
+    fi
+else
+    echo "FAILED"
+    exit 1
+fi
 
 ######################################################################
 # Write Makefile.config
